# Generated by Django 5.0.4 on 2024-04-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstcat',
            old_name='m1Fld1',
            new_name='catId',
        ),
        migrations.RenameField(
            model_name='firstcat',
            old_name='m1Fld2',
            new_name='catName',
        ),
        migrations.RenameField(
            model_name='secondcat',
            old_name='m2Fld2',
            new_name='catId',
        ),
        migrations.RenameField(
            model_name='secondcat',
            old_name='m2Fld1',
            new_name='subcatId',
        ),
        migrations.RenameField(
            model_name='secondcat',
            old_name='m2Fld3',
            new_name='subcatName',
        ),
    ]
