# Generated by Django 5.0.4 on 2024-04-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_m1fld1_firstcat_catid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adds',
            old_name='m3Fld1',
            new_name='listingId',
        ),
        migrations.RenameField(
            model_name='adds',
            old_name='m3Fld3',
            new_name='listingName',
        ),
        migrations.RenameField(
            model_name='adds',
            old_name='m3Fld2',
            new_name='subcatId',
        ),
    ]
