# Generated by Django 5.0.4 on 2024-04-13 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_m3fld1_adds_listingid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adds',
            old_name='subcatId',
            new_name='subcat',
        ),
        migrations.RenameField(
            model_name='secondcat',
            old_name='catId',
            new_name='cat',
        ),
    ]
